/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token and get new access token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate refresh token and clear cookie */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated user profile */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories for the authenticated user */
        get: operations["CategoriesController_list"];
        put?: never;
        /** Create a category */
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a category by id */
        get: operations["CategoriesController_getOne"];
        put?: never;
        post?: never;
        /** Soft-delete a category */
        delete: operations["CategoriesController_delete"];
        options?: never;
        head?: never;
        /** Update a category */
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
    "/api/v1/categories/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a soft-deleted category */
        post: operations["CategoriesController_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List goals for the authenticated user */
        get: operations["GoalsController_list"];
        put?: never;
        /** Create a goal with its first instance */
        post: operations["GoalsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a goal with its active instance */
        get: operations["GoalsController_getOne"];
        put?: never;
        post?: never;
        /** Soft-delete a goal */
        delete: operations["GoalsController_delete"];
        options?: never;
        head?: never;
        /** Update goal metadata */
        patch: operations["GoalsController_update"];
        trace?: never;
    };
    "/api/v1/goals/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a soft-deleted goal */
        post: operations["GoalsController_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{id}/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all instances (cycle history) for a goal */
        get: operations["GoalsController_listInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goal-instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a goal instance with its steps */
        get: operations["GoalInstancesController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update goal instance status manually */
        patch: operations["GoalInstancesController_updateStatus"];
        trace?: never;
    };
    "/api/v1/goal-instances/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force-complete a goal instance; creates next cycle if CYCLIC */
        post: operations["GoalInstancesController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a step for a goal instance */
        post: operations["StepsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/steps/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create several steps at once as a linked recurring group */
        post: operations["StepsController_createBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/steps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a step by id */
        get: operations["StepsController_getOne"];
        put?: never;
        post?: never;
        /** Soft-delete a step */
        delete: operations["StepsController_delete"];
        options?: never;
        head?: never;
        /** Update step progress (current, done, currentStatusId); recalculates GoalInstance.progress */
        patch: operations["StepsController_updateProgress"];
        trace?: never;
    };
    "/api/v1/steps/{id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update step metadata (title, description, weight, order, dates) */
        patch: operations["StepsController_updateMetadata"];
        trace?: never;
    };
    "/api/v1/steps/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a soft-deleted step */
        post: operations["StepsController_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/steps/{id}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change step order within its goal instance */
        post: operations["StepsController_reorder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent activity for the authenticated user (cursor pagination) */
        get: operations["ActivityController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary with streak and category breakdown */
        get: operations["DashboardController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get progress timeline data for charts */
        get: operations["DashboardController_timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get goals and steps with dates in a range */
        get: operations["DashboardController_calendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get upcoming goals and steps ordered by end date */
        get: operations["DashboardController_upcoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all soft-deleted items for the authenticated user */
        get: operations["TrashController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash/restore/{entity}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a soft-deleted entity from trash */
        post: operations["TrashController_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash/{entity}/{id}/permanent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently delete a soft-deleted entity (irreversible) */
        delete: operations["TrashController_permanentDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
            /** @example John Doe */
            name: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        CreateCategoryDto: {
            /** @example Health */
            name: string;
            /** @example All health-related goals */
            description?: string;
            /** @example #4CAF50 */
            color?: string;
            /** @example heart */
            icon?: string;
        };
        UpdateCategoryDto: {
            /** @example Health */
            name?: string;
            /** @example All health-related goals */
            description?: Record<string, never> | null;
            /** @example #4CAF50 */
            color?: Record<string, never> | null;
            /** @example heart */
            icon?: Record<string, never> | null;
        };
        CreateGoalDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            categoryId: string;
            /** @example Run 5k every day */
            name: string;
            /** @example Build a daily running habit */
            description?: string;
            /**
             * @example CYCLIC
             * @enum {string}
             */
            type: "CONCLUSIVE" | "CYCLIC";
            /**
             * @description Required when type is CYCLIC
             * @example DAILY
             * @enum {string}
             */
            cyclePeriod?: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY" | "CUSTOM_DAYS";
            /**
             * @description Required when cyclePeriod is CUSTOM_DAYS
             * @example 14
             */
            customCycleDays?: number;
            /**
             * @description CYCLIC only: when a period rolls over, clone the previous steps with adapted dates (default true). False starts each period empty.
             * @example true
             */
            cloneStepsOnRenewal?: boolean;
        };
        UpdateGoalDto: {
            /** @example Run 5k every day */
            name?: string;
            /** @example Build a daily running habit */
            description?: string | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            categoryId?: string;
            /**
             * @example WEEKLY
             * @enum {string}
             */
            cyclePeriod?: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY" | "CUSTOM_DAYS";
            /** @example 14 */
            customCycleDays?: number;
            /** @example true */
            cloneStepsOnRenewal?: boolean;
        };
        UpdateGoalInstanceStatusDto: {
            /**
             * @example ARCHIVED
             * @enum {string}
             */
            status: "IN_PROGRESS" | "COMPLETED" | "FAILED" | "ARCHIVED";
        };
        StatusOptionDto: {
            /** @example not-started */
            id: string;
            /** @example Not Started */
            label: string;
            /** @example 0 */
            percentage: number;
            /** @example 0 */
            order: number;
        };
        CreateStepDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            goalInstanceId: string;
            /**
             * @example PROGRESS_BAR
             * @enum {string}
             */
            type: "PROGRESS_BAR" | "CHECK" | "STATUS" | "COUNTER";
            /** @example Complete chapter 1 */
            title: string;
            /** @example Read pages 1–30 */
            description?: string;
            /**
             * @description Weight for weighted-average progress (default 1)
             * @example 1.5
             */
            weight?: number;
            /**
             * @description Display order within the goal instance
             * @example 0
             */
            order: number;
            /**
             * @description Unit label (PROGRESS_BAR and COUNTER)
             * @example pages
             */
            unit?: string;
            /**
             * @description Initial current value (PROGRESS_BAR, COUNTER)
             * @example 0
             */
            current?: number;
            /**
             * @description Target value — required for PROGRESS_BAR
             * @example 100
             */
            target?: number;
            /**
             * @description Max value — required for COUNTER
             * @example 50
             */
            max?: number;
            /**
             * @description Min value for COUNTER (default 0)
             * @example 0
             */
            min?: number;
            /**
             * @description Initial done state for CHECK
             * @example false
             */
            done?: boolean;
            /** @description Status options — required for STATUS */
            statuses?: components["schemas"]["StatusOptionDto"][];
            /**
             * @description Active status id — required for STATUS
             * @example not-started
             */
            currentStatusId?: string;
            /** @example 2025-01-01T00:00:00.000Z */
            startDate?: string;
            /** @example 2025-03-31T00:00:00.000Z */
            endDate?: string;
            /** @example 60 */
            estimatedDurationMinutes?: number;
            /**
             * @description Concrete calendar date this step is scheduled for (CYCLIC)
             * @example 2025-01-06T00:00:00.000Z
             */
            scheduledDate?: string;
        };
        CreateStepBatchItemDto: {
            /**
             * @example PROGRESS_BAR
             * @enum {string}
             */
            type: "PROGRESS_BAR" | "CHECK" | "STATUS" | "COUNTER";
            /** @example Complete chapter 1 */
            title: string;
            /** @example Read pages 1–30 */
            description?: string;
            /**
             * @description Weight for weighted-average progress (default 1)
             * @example 1.5
             */
            weight?: number;
            /**
             * @description Unit label (PROGRESS_BAR and COUNTER)
             * @example pages
             */
            unit?: string;
            /**
             * @description Initial current value (PROGRESS_BAR, COUNTER)
             * @example 0
             */
            current?: number;
            /**
             * @description Target value — required for PROGRESS_BAR
             * @example 100
             */
            target?: number;
            /**
             * @description Max value — required for COUNTER
             * @example 50
             */
            max?: number;
            /**
             * @description Min value for COUNTER (default 0)
             * @example 0
             */
            min?: number;
            /**
             * @description Initial done state for CHECK
             * @example false
             */
            done?: boolean;
            /** @description Status options — required for STATUS */
            statuses?: components["schemas"]["StatusOptionDto"][];
            /**
             * @description Active status id — required for STATUS
             * @example not-started
             */
            currentStatusId?: string;
            /** @example 2025-01-01T00:00:00.000Z */
            startDate?: string;
            /** @example 2025-03-31T00:00:00.000Z */
            endDate?: string;
            /** @example 60 */
            estimatedDurationMinutes?: number;
            /**
             * @description Concrete calendar date this step is scheduled for (CYCLIC)
             * @example 2025-01-06T00:00:00.000Z
             */
            scheduledDate?: string;
        };
        CreateStepsBatchDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            goalInstanceId: string;
            /** @example 0 */
            baseOrder: number;
            steps: components["schemas"]["CreateStepBatchItemDto"][];
        };
        UpdateStepMetadataDto: {
            /** @example Complete chapter 2 */
            title?: string;
            /** @example Read pages 31–60 */
            description?: string | null;
            /** @example 2 */
            weight?: number;
            /** @example 1 */
            order?: number;
            /** @example 2025-02-01T00:00:00.000Z */
            startDate?: string;
            /** @example 2025-04-30T00:00:00.000Z */
            endDate?: string;
            /** @example 45 */
            estimatedDurationMinutes?: number;
            /**
             * @description Concrete calendar date this step is scheduled for (CYCLIC)
             * @example 2025-01-06T00:00:00.000Z
             */
            scheduledDate?: string;
        };
        UpdateStepProgressDto: {
            /**
             * @description New current value for PROGRESS_BAR or COUNTER
             * @example 42
             */
            current?: number;
            /**
             * @description New done state for CHECK
             * @example true
             */
            done?: boolean;
            /**
             * @description New active status id for STATUS
             * @example in-progress
             */
            currentStatusId?: string;
        };
        ReorderStepDto: {
            /**
             * @description New 0-based position for this step
             * @example 2
             */
            newOrder: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_list: {
        parameters: {
            query?: {
                includeDeleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_list: {
        parameters: {
            query?: {
                categoryId?: string;
                type?: "CONCLUSIVE" | "CYCLIC";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGoalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalsController_listInstances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalInstancesController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalInstancesController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGoalInstanceStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoalInstancesController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StepsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStepDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StepsController_createBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStepsBatchDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StepsController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StepsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StepsController_updateProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStepProgressDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StepsController_updateMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStepMetadataDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StepsController_restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StepsController_reorder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderStepDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ActivityController_list: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_timeline: {
        parameters: {
            query?: {
                range?: "week" | "month" | "year";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_calendar: {
        parameters: {
            query: {
                /** @description ISO date string */
                from: string;
                /** @description ISO date string */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_upcoming: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrashController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrashController_restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity: "category" | "goal" | "step";
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrashController_permanentDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity: "category" | "goal" | "step";
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
