/**
 * Centralized icon exports.
 * Re-exports lucide-react icons with consistent defaults via the Icon atom.
 * Import icons from here — never directly from lucide-react in feature code.
 */
export {
  Activity,
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  Bell,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  Clock,
  Copy,
  Edit,
  Eye,
  EyeOff,
  Filter,
  Flame,
  FolderOpen,
  GripVertical,
  Hash,
  Home,
  Info,
  Layers,
  LayoutDashboard,
  List,
  Loader2,
  LogOut,
  Menu,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Pencil,
  Plus,
  RefreshCcw,
  RotateCcw,
  Search,
  Settings,
  Settings2,
  SlidersHorizontal,
  Star,
  Sun,
  Target,
  Trash2,
  TrendingUp,
  User,
  X,
  Zap,
} from "lucide-react";

export { Icon } from "@/shared/ui-kit/atoms/Icon";
export type { IconProps, IconSize } from "@/shared/ui-kit/atoms/Icon";
